
before_script:
  - "source ~gitlab-runner/cicd_support/cicd_support.shinc"


after_script:
  - "echo Test Complete."

stages:
  - clean
  - build
  - test
  - fuzz
  - deploy


#
# Cleaning
#
do-clean-ubuntu18:
  stage: clean
  script:
    - ./cicd_testing/do-clean.sh
  tags:
    - ubuntu18

do-clean-ubuntu16:
  stage: clean
  script:
    - ./cicd_testing/do-clean.sh
  tags:
    - ubuntu16

do-clean-arm32:
  stage: clean
  script:
    - ./cicd_testing/do-clean.sh
  tags:
    - arm32

do-clean-arm64:
  stage: clean
  script:
    - ./cicd_testing/do-clean.sh
  tags:
    - arm64

do-clean-centos76:
  stage: clean
  script:
    - ./cicd_testing/do-clean.sh
  tags:
    - centos76

#
# Building
#
do-build-ubuntu18:
  stage: build
  script:
    - ./cicd_testing/do-build.sh
  tags:
    - ubuntu18

do-build-ubuntu16:
  stage: build
  script:
    - ./cicd_testing/do-build.sh
  tags:
    - ubuntu16

do-build-arm64:
  stage: build
  script:
    - ./cicd_testing/do-build.sh
  tags:
    - arm64

do-build-arm32:
  stage: build
  script:
    - ./cicd_testing/do-build.sh
  tags:
    - arm32

do-build-centos76:
  stage: build
  script:
    - ./cicd_testing/do-build.sh
  tags:
    - centos76


#
# Testing
#
do-test-ubuntu18:
  stage: test
  script:
    - ./cicd_testing/do-test.sh
  tags:
    - ubuntu18

do-test-ubuntu16:
  stage: test
  script:
    - ./cicd_testing/do-test.sh
  tags:
    - ubuntu16

do-test-arm32:
  stage: test
  script:
    - ./cicd_testing/do-test.sh
  tags:
    - arm32

do-test-arm64:
  stage: test
  script:
    - ./cicd_testing/do-test.sh
  tags:
    - arm64


do-test-centos76:
  stage: test
  script:
    - ./cicd_testing/do-test.sh
  tags:
    - centos76


#
# Turbo Fuzzing
#
do-fuzz-ubuntu18:
  stage: fuzz
  script:
    - ./cicd_testing/do-fuzz.sh
  tags:
    - libehpfuzzpod

#
# Deploy
#
do-deploy-ubuntu18:
  stage: deploy
  script:
    - ./cicd_testing/do-deploy.sh
  tags:
    - ubuntu18
